services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: prodapt-postgres

    environment:
      POSTGRES_DB: support_db
      POSTGRES_USER: support_user
      POSTGRES_PASSWORD: support_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: